spring:
  application:
    name: nails

  datasource:
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/iterations.yaml
    contexts: ${spring.profiles.active}

  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8080